### ISSUE TITLE
support for wheel packages?

### ISSUE THREAD

**Issue by osallou** [p1otr/pypi2deb#12]
Hi,
I tried to use py2dsp for a wheel package in pypi but it fails (not finding a version)

    $ py2dsp biomaj-core
    Traceback (most recent call last):
      File "/usr/bin/py2dsp", line 136, in <module>
        loop.run_until_complete(main(args))
      File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
        return future.result()
      File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
        raise self._exception
      File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
        result = coro.send(None)
      File "/usr/bin/py2dsp", line 61, in main
        fname = yield from download(name, destdir=args.root)
      File "/usr/share/pypi2deb/pypi2deb/pypi.py", line 133, in download
        raise Exception('source package not available on PyPI')
    Exception: source package not available on PyPI

Package on pypi is a wheel package:

    biomaj_core-3.0.9-py2.py3-none-any.whl (md5) | Python Wheel | py2.py3 | 2017-06-20 | 12KB

Is issue related to the fact it is a wheel package?

**Comment by sandrotosi** [comment]
yes, it is because it's a wheel and not a source distribution. maybe you can try the new github integration to start from the GH project repo

**Comment by sandrotosi** [comment]
py2dsp converts a python source tarball to a debian source package. so we required upstream to release a source tarball either on PyPI or via github tags/releases, and we cannot use a wheel for it.

i believe this issue can be closed as wontfix
