### ISSUE TITLE
RuntimeError: Event loop is closed

### ISSUE THREAD

**Issue by spanezz** [p1otr/pypi2deb#6]
Hello,

thank you for pypi2deb. I'm trying to integrate it in the workflow to manage non-debian dependencies in my workplace.

When trying to debianise `django-countries` I get this error:
```
$ py2dsp -v django-countries
D: py2dsp py2dsp:138: version: 1.20151008
D: py2dsp py2dsp:139: ['/usr/bin/py2dsp', '-v', 'django-countries']
D: py2dsp py2dsp:42: args: Namespace(application=False, build=False, clean=False, distribution='UNRELEASED', message='converte0~py2deb', name='django-countries', profile=None, quiet=False, revision='0~py2deb', root='/home/enrico/…/result', verbose=True)
D: py2dsp tools:109: invoking: ['dpkg-buildpackage', '-S', '-us', '-uc', '-I.git', '-i.git'] in /home/enrico/…/result/django-countries-4.0
dpkg-buildpackage: info: source package django-countries
dpkg-buildpackage: info: source version 4.0-0~pypi2deb
dpkg-buildpackage: info: source distribution UNRELEASED
dpkg-buildpackage: info: source changed by Enrico Zini <enrico@debian.org>
 dpkg-source -I.git -i.git --before-build django-countries-4.0
dpkg-source: info: using options from django-countries-4.0/debian/source/options: --extend-diff-ignore=^[^/]+.egg-info/
 fakeroot debian/rules clean
dh clean --with python2,python3 --buildsystem=pybuild
   dh_testdir -O--buildsystem=pybuild
   dh_auto_clean -O--buildsystem=pybuild
I: pybuild base:184: python2.7 setup.py clean 
running clean
removing '/home/enrico/…/result/django-countries-4.0/.pybuild/pythonX.Y_2.7/build' (and everything under it)
'build/bdist.linux-x86_64' does not exist -- can't clean it
'build/scripts-2.7' does not exist -- can't clean it
I: pybuild base:184: python3.5 setup.py clean 
running clean
removing '/home/enrico/…/result/django-countries-4.0/.pybuild/pythonX.Y_3.5/build' (and everything under it)
'build/bdist.linux-x86_64' does not exist -- can't clean it
'build/scripts-3.5' does not exist -- can't clean it
   dh_clean -O--buildsystem=pybuild
 dpkg-source -I.git -i.git -b django-countries-4.0
dpkg-source: info: using options from django-countries-4.0/debian/source/options: --extend-diff-ignore=^[^/]+.egg-info/
dpkg-source: info: using source format '3.0 (quilt)'
dpkg-source: info: building django-countries using existing ./django-countries_4.0.orig.tar.gz
dpkg-source: info: building django-countries in django-countries_4.0-0~pypi2deb.debian.tar.xz
dpkg-source: info: building django-countries in django-countries_4.0-0~pypi2deb.dsc
 dpkg-genchanges --build=source >../django-countries_4.0-0~pypi2deb_source.changes
dpkg-genchanges: info: including full source code in upload
 dpkg-source -I.git -i.git --after-build django-countries-4.0
dpkg-source: info: using options from django-countries-4.0/debian/source/options: --extend-diff-ignore=^[^/]+.egg-info/
dpkg-buildpackage: info: full upload (original source is included)
E: py2dsp base_events:1228: Fatal write error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f68b76ec978>
transport: <_SelectorSocketTransport fd=6>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 730, in write
    n = self._sock.send(data)
OSError: [Errno 9] Bad file descriptor
E: py2dsp base_events:1228: Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f68b76ec978>
transport: <_SelectorSocketTransport closing fd=6>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 730, in write
    n = self._sock.send(data)
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/sslproto.py", line 638, in _process_write_backlog
    self._transport.write(chunk)
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 734, in write
    self._fatal_error(exc, 'Fatal write error on socket transport')
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 614, in _fatal_error
    self._force_close(exc)
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 626, in _force_close
    self._loop.call_soon(self._call_connection_lost, exc)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 567, in call_soon
    handle = self._call_soon(callback, args)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 576, in _call_soon
    self._check_closed()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 356, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

I do seem to still get the package in `results/` debianised right, though, so this doesn't seem to be a blocker so far.

**Comment by p1otr** [comment]
> D: py2dsp py2dsp:138: version: 1.20151008

I remember having this problem some time ago and IIRC it was fixed in
python3.5 or aiohttp. Does the combination of python3.5, python3-aiohttp
and pypi2deb from unstable work for you?

**Comment by spanezz** [comment]
I confirm that the problem went away after upgrading `python3.5` from `3.5.2-6+b1` to `3.5.2-7`.

**Comment by p1otr** [comment]
[Enrico Zini, 2016-11-09]

> I confirm that the problem went away after upgrading `python3.5` from
> `3.5.2-6+b1` to `3.5.2-7`.

weird, I was pretty sure it was actually aiohttp (I was using version
that wasn't uploaded to Debian unstable so I didn't see this error in
months).

Anyway, glad it works for you now. There's a newer version in unstable /
github, BTW

**Comment by sandrotosi** [comment]
i believe this issue can be closed as fixed
